#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : graphene
Version  : 1.6.0
Release  : 1
URL      : https://download.gnome.org/sources/graphene/1.6/graphene-1.6.0.tar.xz
Source0  : https://download.gnome.org/sources/graphene/1.6/graphene-1.6.0.tar.xz
Summary  : Math classes for graphic libraries
Group    : Development/Tools
License  : MIT
Requires: graphene-lib
Requires: graphene-doc
Requires: graphene-data
BuildRequires : docbook-xml
BuildRequires : gobject-introspection-dev
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : libxslt-bin
BuildRequires : meson
BuildRequires : ninja
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gobject-2.0)
BuildRequires : python3
BuildRequires : sed

%description
No detailed description available

%package data
Summary: data components for the graphene package.
Group: Data

%description data
data components for the graphene package.


%package dev
Summary: dev components for the graphene package.
Group: Development
Requires: graphene-lib
Requires: graphene-data
Provides: graphene-devel

%description dev
dev components for the graphene package.


%package doc
Summary: doc components for the graphene package.
Group: Documentation

%description doc
doc components for the graphene package.


%package lib
Summary: lib components for the graphene package.
Group: Libraries
Requires: graphene-data

%description lib
lib components for the graphene package.


%prep
%setup -q -n graphene-1.6.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1518729848
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1518729848
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/Graphene-1.0.typelib
/usr/share/gir-1.0/*.gir

%files dev
%defattr(-,root,root,-)
/usr/include/graphene-1.0/graphene-box.h
/usr/include/graphene-1.0/graphene-euler.h
/usr/include/graphene-1.0/graphene-frustum.h
/usr/include/graphene-1.0/graphene-gobject.h
/usr/include/graphene-1.0/graphene-macros.h
/usr/include/graphene-1.0/graphene-matrix.h
/usr/include/graphene-1.0/graphene-plane.h
/usr/include/graphene-1.0/graphene-point.h
/usr/include/graphene-1.0/graphene-point3d.h
/usr/include/graphene-1.0/graphene-quad.h
/usr/include/graphene-1.0/graphene-quaternion.h
/usr/include/graphene-1.0/graphene-ray.h
/usr/include/graphene-1.0/graphene-rect.h
/usr/include/graphene-1.0/graphene-simd4f.h
/usr/include/graphene-1.0/graphene-simd4x4f.h
/usr/include/graphene-1.0/graphene-size.h
/usr/include/graphene-1.0/graphene-sphere.h
/usr/include/graphene-1.0/graphene-triangle.h
/usr/include/graphene-1.0/graphene-types.h
/usr/include/graphene-1.0/graphene-vec2.h
/usr/include/graphene-1.0/graphene-vec3.h
/usr/include/graphene-1.0/graphene-vec4.h
/usr/include/graphene-1.0/graphene-version-macros.h
/usr/include/graphene-1.0/graphene-version.h
/usr/include/graphene-1.0/graphene.h
/usr/lib64/graphene-1.0/include/graphene-config.h
/usr/lib64/libgraphene-1.0.so
/usr/lib64/pkgconfig/graphene-1.0.pc
/usr/lib64/pkgconfig/graphene-gobject-1.0.pc

%files doc
%defattr(-,root,root,-)
/usr/share/gtk-doc/html/graphene/annotation-glossary.html
/usr/share/gtk-doc/html/graphene/api-index.html
/usr/share/gtk-doc/html/graphene/ch01.html
/usr/share/gtk-doc/html/graphene/deprecated-api-index.html
/usr/share/gtk-doc/html/graphene/graphene-Box.html
/usr/share/gtk-doc/html/graphene/graphene-Euler.html
/usr/share/gtk-doc/html/graphene/graphene-Frustum.html
/usr/share/gtk-doc/html/graphene/graphene-GObject-integration.html
/usr/share/gtk-doc/html/graphene/graphene-Matrix.html
/usr/share/gtk-doc/html/graphene/graphene-Plane.html
/usr/share/gtk-doc/html/graphene/graphene-Point.html
/usr/share/gtk-doc/html/graphene/graphene-Point3D.html
/usr/share/gtk-doc/html/graphene/graphene-Quad.html
/usr/share/gtk-doc/html/graphene/graphene-Quaternion.html
/usr/share/gtk-doc/html/graphene/graphene-Ray.html
/usr/share/gtk-doc/html/graphene/graphene-Rectangle.html
/usr/share/gtk-doc/html/graphene/graphene-SIMD-matrix.html
/usr/share/gtk-doc/html/graphene/graphene-SIMD-vector.html
/usr/share/gtk-doc/html/graphene/graphene-Size.html
/usr/share/gtk-doc/html/graphene/graphene-Sphere.html
/usr/share/gtk-doc/html/graphene/graphene-Triangle.html
/usr/share/gtk-doc/html/graphene/graphene-Vectors.html
/usr/share/gtk-doc/html/graphene/graphene-Versioning-information.html
/usr/share/gtk-doc/html/graphene/graphene.devhelp2
/usr/share/gtk-doc/html/graphene/home.png
/usr/share/gtk-doc/html/graphene/index.html
/usr/share/gtk-doc/html/graphene/ix03.html
/usr/share/gtk-doc/html/graphene/ix04.html
/usr/share/gtk-doc/html/graphene/ix05.html
/usr/share/gtk-doc/html/graphene/ix06.html
/usr/share/gtk-doc/html/graphene/left-insensitive.png
/usr/share/gtk-doc/html/graphene/left.png
/usr/share/gtk-doc/html/graphene/object-tree.html
/usr/share/gtk-doc/html/graphene/rectangle-intersection.png
/usr/share/gtk-doc/html/graphene/rectangle-union.png
/usr/share/gtk-doc/html/graphene/rectangle.png
/usr/share/gtk-doc/html/graphene/right-insensitive.png
/usr/share/gtk-doc/html/graphene/right.png
/usr/share/gtk-doc/html/graphene/style.css
/usr/share/gtk-doc/html/graphene/triangle-barycentric.png
/usr/share/gtk-doc/html/graphene/up-insensitive.png
/usr/share/gtk-doc/html/graphene/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/libgraphene-1.0.so.0
/usr/lib64/libgraphene-1.0.so.0.600.0
